export function renderFaq(): string {
  const items = [
    ["Do czego służy aplikacja?", "Allegro Monitor obserwuje wskazane wyniki wyszukiwania w otwartych kartach Vivaldi. Rozszerzenie odczytuje produkty, a prywatny serwer zapisuje stan, wykrywa nowości, pokazuje panel i wysyła powiadomienia Telegram."],
    ["Czy Vivaldi i monitorowana karta muszą być otwarte?", "Tak. Sprawdzanie odbywa się w prawdziwej karcie przeglądarki, dlatego Vivaldi musi działać, komputer nie może być uśpiony, a karta wyszukiwania musi pozostać otwarta. Nie musi być aktywna ani widoczna na ekranie."],
    ["Co oznaczają statusy monitora?", "„Działa” oznacza, że przynajmniej jedno sparowane urządzenie ma otwartą kartę i wysłało niedawny heartbeat. „Brak otwartej karty” oznacza brak aktywnego urządzenia. „Wymaga uwagi” sygnalizuje błąd odczytu, blokadę lub captcha. „Wstrzymany” oznacza ręczne wyłączenie w panelu."],
    ["Jak szybko wykrywane jest zamknięcie karty?", "Rozszerzenie reaguje na otwarcie i zamknięcie karty niemal natychmiast oraz wysyła heartbeat co minutę. Jeśli przeglądarka lub komputer wyłączy się bez wysłania zdarzenia, obecność wygasa po około trzech minutach."],
    ["Co się dzieje, gdy kilka osób obserwuje ten sam adres?", "Każde sparowane rozszerzenie raportuje obecność osobno. Monitor pozostaje aktywny, dopóki przynajmniej jedna osoba ma otwartą właściwą kartę. Zamknięcie lub odłączenie karty przez jedną osobę nie zatrzymuje monitora działającego u drugiej."],
    ["Dlaczego pierwsze sprawdzenie nie wysyła powiadomień?", "Pierwszy odczyt tworzy punkt odniesienia. Wszystkie widoczne wtedy pozycje są traktowane jako stan początkowy, dzięki czemu instalacja nie generuje dziesiątek fałszywych alertów."],
    ["Co oznacza +N?", "Plakietka przy monitorze pokazuje liczbę nowych pozycji wykrytych wyłącznie w ostatnim udanym sprawdzeniu. Po kolejnym sprawdzeniu bez nowości znika. Osobna statystyka „Wykryte nowości” pozostaje łącznym wynikiem od utworzenia punktu odniesienia."],
    ["Które oferty są subtelnie wyróżnione?", "Zielone oznaczenie „Nowa” otrzymują tylko pozycje wykryte jako nowe podczas ostatniego udanego sprawdzenia danego monitora. Wyróżnienie znika po następnym sprawdzeniu bez nowych pozycji."],
    ["Jak działają interwały?", "Dostępne są interwały 1, 5, 15, 30 i 60 minut. Jedna minuta jest przydatna do testów, ale częste przeładowania zwiększają ryzyko captcha lub blokady Allegro. Do zwykłej pracy rozsądniejsze jest 5–15 minut."],
    ["Co się stanie po captcha lub blokadzie Allegro?", "Rozszerzenie nie omija zabezpieczeń. Zgłasza problem, pokazuje powiadomienie i pozostawia kartę do ręcznego potwierdzenia. Po rozwiązaniu captcha kolejne sprawdzenie może wrócić do normalnej pracy."],
    ["Jak działają dokładne wykluczenia?", "Wykluczenie używa pełnego identyfikatora produktu lub oferty Allegro, a nie luźnego fragmentu tytułu. Ukrywa więc dokładne wydanie albo pojedynczą ofertę i nie powinno wykluczyć innej poszukiwanej książki. Regułę można cofnąć na karcie monitora bez wywołania fałszywego alertu."],
    ["Co jest przechowywane w SQLite?", "Konfiguracja monitorów, skróty tokenów rozszerzeń, identyfikatory i metadane ofert, czasy pierwszego i ostatniego zauważenia, liczniki, wykluczenia oraz obecność urządzeń. Baza nie zawiera cookies, hasła Allegro, profilu Vivaldi ani tokenu Telegrama."],
    ["Czy baza rośnie bez końca?", "Nieobecna pozycja jest domyślnie usuwana po pięciu kolejnych udanych sprawdzeniach. Aktualnie widoczne produkty pozostają jako punkt odniesienia, a krótki bufor zapobiega ponownemu uznawaniu chwilowo znikających ofert za nowe."],
    ["Jak skonfigurować Telegram dla kilku osób lub grupy?", "Każdy odbiorca musi najpierw napisać do bota, a bot musi zostać dodany do grupy. W Portainerze TELEGRAM_CHAT_IDS przyjmuje identyfikatory oddzielone przecinkami. Bot nie musi być administratorem, a jego tokenu nie wolno przekazywać użytkownikom."],
    ["Ile nieudanych prób logowania blokuje dostęp?", "Aplikacja dopuszcza 20 błędnych prób Basic Auth z danego źródła w oknie 15 minut liczonym od pierwszej próby. Od 21. błędnej próby zwraca kod 429 do końca tego okna. Poprawne dane są sprawdzane przed limitem, więc właściciel nadal może się zalogować; udane logowanie zeruje licznik. Użytkownicy wychodzący przez to samo proxy mogą być widziani jako jedno źródło."],
    ["Jak zabezpieczone jest parowanie rozszerzenia?", "Kod parowania jest losowy, jednorazowy i ważny 10 minut. Dopuszczalne jest 12 prób w ciągu 15 minut z danego źródła; kolejne zwracają 429. Udane parowanie zeruje licznik i wydaje długi losowy token, którego skrót jest przechowywany w bazie."],
    ["Czy usunięcie monitora z rozszerzenia kasuje historię?", "Nie. Przycisk w popupie odłącza tylko bieżące urządzenie. Monitor bez aktywnych urządzeń pozostaje w panelu jako nieaktywny. Trwałe usunięcie konfiguracji, historii i wykluczeń wymaga świadomego użycia przycisku „Usuń” w panelu WWW."],
    ["Jak aktualizować aplikację i rozszerzenie?", "Serwer aktualizuje się przez ponowne pobranie obrazu w Portainerze. Rozszerzenie jest instalowane jako rozpakowane, więc po wydaniu nowej wersji trzeba pobrać ZIP, nadpisać jego katalog i kliknąć „Przeładuj” na vivaldi://extensions. Ponowne parowanie zwykle nie jest potrzebne."],
    ["Jakie dane opuszczają przeglądarkę?", "Do prywatnego serwera trafia adres monitorowanego wyszukiwania oraz podstawowe metadane znalezionych produktów: identyfikator, tytuł, URL, cena i miniatura. Cookies, dane logowania i pozostała historia przeglądania nie są wysyłane."],
    ["Jak bezpiecznie wystawić panel?", "Cloudflare Tunnel powinien być jedyną drogą z Internetu. Nie należy przekierowywać portu aplikacji na routerze. Panel wymaga silnego hasła, a token Telegrama powinien pozostawać wyłącznie w zmiennych Portainera. Dodatkową warstwą może być Cloudflare Access z osobnym wyjątkiem dla API rozszerzenia."],
  ];
  return `<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>FAQ · Allegro Monitor</title><script>try{const t=localStorage.getItem('theme');if(t)document.documentElement.dataset.theme=t}catch{}</script><style>
  :root{--bg:#f3f4f6;--surface:#fff;--text:#17181a;--muted:#686c73;--line:#e2e4e8;--brand:#d8612c;--brand-soft:#faeee8;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color-scheme:light}:root[data-theme="dark"]{--bg:#101113;--surface:#191b1f;--text:#f2f3f4;--muted:#a5a9b0;--line:#31343a;--brand:#df7445;--brand-soft:#35251e;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);line-height:1.55}.shell{width:min(860px,calc(100% - 32px));margin:auto;padding:32px 0 64px}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:30px}.back{color:var(--brand);font-weight:700;text-decoration:none}.theme{display:grid;place-items:center;width:40px;height:40px;border:1px solid var(--line);border-radius:10px;background:var(--surface);color:var(--text);font-size:19px;cursor:pointer}.hero{margin-bottom:24px}.eyebrow{color:var(--brand);font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.hero h1{font-size:clamp(30px,5vw,48px);line-height:1.05;letter-spacing:-.035em;margin:8px 0 12px}.hero p{color:var(--muted);max-width:680px}.questions{display:grid;gap:10px}details{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:0 18px}details[open]{border-color:color-mix(in srgb,var(--brand) 45%,var(--line))}summary{cursor:pointer;font-weight:750;padding:16px 30px 16px 0;position:relative;list-style:none}summary::-webkit-details-marker{display:none}summary:after{content:"+";position:absolute;right:2px;color:var(--brand);font-size:20px;top:12px}details[open] summary:after{content:"−"}details p{color:var(--muted);margin:0;padding:0 0 17px}footer{color:var(--muted);font-size:13px;margin-top:28px}@media(max-width:600px){.shell{width:min(100% - 20px,860px);padding-top:20px}}
  </style></head><body><main class="shell"><div class="top"><a class="back" href="/">← Panel</a><button class="theme" id="theme" aria-label="Zmień motyw">◐</button></div><section class="hero"><span class="eyebrow">Allegro Monitor</span><h1>Najczęściej zadawane pytania</h1><p>Najważniejsze informacje o działaniu monitorów, rozszerzeniu, powiadomieniach, danych i bezpieczeństwie.</p></section><section class="questions">${items.map(([question, answer]) => `<details><summary>${question}</summary><p>${answer}</p></details>`).join("")}</section><footer>Allegro Monitor · kCn & Codex · dla Wioli 📚</footer></main><script>const r=document.documentElement,b=document.getElementById('theme');b.onclick=()=>{const c=r.dataset.theme||((matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light');r.dataset.theme=c==='dark'?'light':'dark';localStorage.setItem('theme',r.dataset.theme)}</script></body></html>`;
}
